### ISSUE TITLE
Dynamic width

### ISSUE THREAD

**Issue by M21B8** [standup75/cropme#51] opened 2015-11-02 12:42 UTC
The documentation says that the width attribute is optional, however, if you leave this off, while it does set the image to fit the page, nothing else works, you don't get a bounding box, so all the sizings inside the progess event are all NaN

**Comment by standup75** [comment] 2015-11-02 14:32
I will look into this

**Comment by webmatze** [comment] 2015-11-04 18:10
I need a fix for this too.

The problem is in [line 90 of cropme.coffee](https://github.com/standup75/cropme/blob/master/scripts/directives/cropme.coffee#L90)

You are calculating a zoom with the **scope.width** but this is undefined.

But if I set the width I can not load images smaller then this width, which I need it to be able to.

**Comment by standup75** [comment] 2015-11-06 14:53
see version 0.4.1

**Closed by standup75** 2015-11-06 14:53 UTC
